<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

	<ItemGroup>
		<Reference Include="C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.12\*.dll" Exclude="C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.12\aspnetcorev2_inprocess.dll">
			<Private>False</Private>
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.5" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.5" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="wwwroot\**\*" />
	</ItemGroup>


</Project>
